apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 5Gi  # 원하는 스토리지 크기 설정
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: /opt/db/postgres  # 호스트의 디렉터리
  persistentVolumeReclaimPolicy: Retain  # PV를 삭제해도 데이터 유지
