apiVersion: apps/v1
kind: StatefulSet  # StatefulSet 사용
metadata:
  name: postgres
spec:
  serviceName: postgres-service  # Headless Service
  replicas: 1  # PostgreSQL 인스턴스 수
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14  # PostgreSQL 이미지
          ports:
            - containerPort: 5432  # PostgreSQL 기본 포트
          env:
            #- name: POSTGRES_DB
            #  value: mydatabase  # 데이터베이스 이름
            #- name: POSTGRES_USER
            #  value: myuser  # 사용자 이름
            - name: POSTGRES_PASSWORD
              value: mypassword  # 사용자 비밀번호
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data  # PostgreSQL 데이터 디렉터리
  volumeClaimTemplates:
   - metadata:
       name: postgres-pvc
     spec:
       accessModes: [ "ReadWriteMany" ]
       resources:
         requests:
           storage: 5Gi
~                                  
